---
strategy: static
no_screen_padding: 'no'
dark_mode: 'no'
static_data: '{}'
polling_verb: get
polling_url: ''
polling_headers: ''
polling_body: ''
id: 100671
dark_mode: 'yes'
custom_fields:
- keyname: wisdom_trmnl
  name: Wisdom Project Quotes
  category: life,productivity
  field_type: author_bio
  description: Display a daily quote from Merlin Mann's "The Wisdom Project" - http://wisdom.limo
  github_url: https://github.com/VisualYeti/wisdom_trmnl
  learn_more_url: http://wisdom.limo
  email_address: support@visualyeti.com
- keyname: quote_size
  field_type: select
  name: Full View Quote Size
  default: 20
  optional: true
  options:
  - Small: 10
  - Medium: 20
  - Large: 30
- keyname: quote_font
  field_type: select
  name: Quote Font
  default: Joan
  optional: true
  options:
  - Joan
  - Caudex
  - Old Standard TT
  - Raleway
  - Rubik
name: The Wisdom Project Quotes
refresh_interval: 1440
